# -*- coding: utf-8 -*-
"""Task 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t5bIzl_IgRSmCVI51oT2bXdKl1SWqK08

# **Task 3**
 **Mohamed sherif Ahmed Abdelhameed**

 **Email:mohamedsherif1304@gmail.com**

 **Mobile:01119434900**
"""

import pandas as pd

# Load the data
file_path = "/content/Employees.csv"
df = pd.read_csv(file_path)
# Print the data
print("Data after reading the CSV file:\n")
print(df)

# 1- Remove any duplicates in the table
df1 = df.drop_duplicates()
print(df)

# 2- Remove any decimal places in the Age column
df['Age'] = df['Age'].round(0).astype(int)
print(df)

# 3- Convert the USD salary to EGP
usd_to_egp_conversion_rate = 50
df['Salary(EGP)'] = df['Salary(USD)'] * usd_to_egp_conversion_rate
print(df)

# 4- Print the statistics
average_age = df['Age'].mean()
median_salary = df['Salary(EGP)'].median()
gender_ratio = df['Gender'].value_counts(normalize=True)

# Print statistics
print(f"Average Age: {average_age:.2f} years")
print(f"Median Salary (EGP): {median_salary:.2f} EGP")
print("Gender Ratio:")
for gender, ratio in gender_ratio.items():
    print(f"  {gender}: {ratio:.2%}")

# 5- New CSV file
output_file_path = "/content/Employees.csv"
df.to_csv(output_file_path, index=False)

print(f"Modified data has been saved to: {output_file_path}")